name: gitsplit
on:
  push:
    branches:
      - main
#   release:
#     types: [published]

jobs:
  gitsplit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: git clone https://github.com/tarekdj/test-monorepo /home/runner/work/tarekdj/test-monorepo && cd /home/runner/work/tarekdj/test-monorepo
      
#       - name: prepare gitsplit
#         run: cp /home/runner/work/tarekdj/test-monorepo/.gitsplit.yml /home/runner/work/tarekdj/test-monorepo/.gitsplit.yml
      
      - name: gitsplit
        run: docker run --rm -t -e GH_TOKEN -v /cache/gitsplit:/cache/gitsplit -v /home/runner/work/tarekdj/test-monorepo:/srv jderusse/gitsplit gitsplit
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
      
      
#       - name: Split repositories
#         uses: docker://jderusse/gitsplit:latest
#         with:
#           args: gitsplit
#         env:
#           GH_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
